apiVersion: v1
kind: Service
metadata:
  name: {{ include "fortigate-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- with .Values.service.labels }}
    {{- toYaml (omit . "helm.sh/chart" "app.kubernetes.io/name" "app.kubernetes.io/instance" "app.kubernetes.io/version" "app.kubernetes.io/managed-by" "app.kubernetes.io/component" "monitoring-job") | nindent 4 }}
    {{- end }}
    {{- include "fortigate-exporter.labels" . | nindent 4 }}
    monitoring-job: {{ .Values.serviceMonitor.jobName | quote }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | quote }}
  selector:
    {{- include "fortigate-exporter.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
