config:
  siteUrl: https://powerdns-admin.uat.example.internal
  csrfCookieSecure: true
  hstsEnabled: true
  serverExternalSsl: true
  sessionCookieSecure: true
  signupEnabled: false

migration:
  mode: argocdHook

postgresql:
  persistence:
    storageClass: example-storage
    size: 10Gi

networkPolicy:
  enabled: true
  web:
    from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: istio-system

route:
  enabled: true
  host: powerdns-admin.uat.example.internal
  gateway:
    resourceNamespace: istio-system
    workloadNamespace: istio-system
  tls:
    certificate:
      namespace: istio-system
