{{- if and .Values.web.enabled .Values.ingress.enabled }}
{{- $annotations := mergeOverwrite (dict) .Values.commonAnnotations .Values.ingress.annotations -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "oxidized.fullname" . | quote }}
  namespace: {{ include "oxidized.namespace" . | quote }}
  labels:
    {{- include "oxidized.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ include "oxidized.fullname" $ | quote }}
                port:
                  name: http
          {{- end }}
    {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
