{{- if and .Values.runtimeSecret.enabled .Values.runtimeSecret.create (not .Values.runtimeSecret.existingSecret) }}
{{- $secretKeys := .Values.runtimeSecret.secretKeys -}}
{{- $data := .Values.runtimeSecret.data -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oxidized.runtimeSecretName" . | quote }}
  namespace: {{ include "oxidized.namespace" . | quote }}
  labels:
    {{- include "oxidized.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  {{ $secretKeys.deviceUsernameKey | quote }}: {{ $data.deviceUsername | quote }}
  {{ $secretKeys.devicePasswordKey | quote }}: {{ $data.devicePassword | quote }}
  {{ $secretKeys.netboxApiTokenKey | quote }}: {{ $data.netboxApiToken | quote }}
  {{ $secretKeys.readonlyDeviceUsernameKey | quote }}: {{ $data.readonlyDeviceUsername | quote }}
  {{ $secretKeys.readonlyDevicePasswordKey | quote }}: {{ $data.readonlyDevicePassword | quote }}
  {{- range $environmentName, $secretKey := $secretKeys.extra }}
  {{ $secretKey | quote }}: {{ get $data.extra $environmentName | quote }}
  {{- end }}
{{- end }}
