{{- if .Values.serviceAccount.create }}
{{- $annotations := mergeOverwrite (dict) .Values.commonAnnotations .Values.serviceAccount.annotations -}}
{{- if eq .Values.migration.mode "argocdHook" -}}
{{- $_ := set $annotations "argocd.argoproj.io/sync-wave" "-30" -}}
{{- end -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "powerdns-admin.serviceAccountName" . | quote }}
  namespace: {{ include "powerdns-admin.namespace" . | quote }}
  labels:
    {{- include "powerdns-admin.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
